### ISSUE TITLE
responsive design problem

### ISSUE THREAD

**Issue by oguzhancevik** [oguzhancevik/oguzhancevik.github.io#1]
responsive design problem

https://oguzhancevik.github.io/poligonar/index.html

**Comment by SafaElmali** [comment]
I want to work on this problem :)

**Comment by oguzhancevik** [comment]
Thank you @SafaElmali. your commit works for me. 
https://github.com/oguzhancevik/oguzhancevik.github.io/commit/c1aca76a3003d1b47967fbb88a5423aea5ae4600
